- roles/keycloak/tasks/main.yml
- roles/keycloak/tasks/start_keycloak.yml
- roles/keycloak/tasks/systemd.yml
- roles/keycloak/templates/standalone-infinispan.xml.j2
- roles/keycloak/templates/standalone.xml.j2
run_once on first node when database config enabled (so the first
node creates the tables), then wakeup all other nodes
fixes #13
> Replace use of serial with run_once

- molecule/default/converge.yml
- molecule/default/verify.yml
- playbooks/keycloak_realm.yml
- playbooks/rhsso.yml
- roles/keycloak/defaults/main.yml
- roles/keycloak/meta/main.yml
- roles/keycloak/tasks/firewalld.yml
- roles/keycloak/tasks/prereqs.yml
- roles/keycloak/vars/main.yml
- roles/keycloak_realm/README.md
- roles/keycloak_realm/defaults/main.yml
- roles/keycloak_realm/vars/main.yml
> move admin pwd param from vars to defaults, add assert

- roles/keycloak_quarkus/tasks/main.yml
The modified tasks require sudo rights to be performed.
Running the whole playbook as sudo will fail on the tasks that are delegated to localhosts (unless you are actually running the playbook as root)
> Use become for tasks that will otherwise fail

- molecule/quarkus/converge.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
If you want to use a certificate for both Keycloak and Nginx, the cert files are quite unlikely to be under `keycloak.home`
Even in case you want to keep the under Keycloak path, you can always define the variable:
```
keycloak_quarkus_cert_file: "{{ keycloak.home }}/conf/my_keycloak_cert.pem"
keycloak_quarkus_key_file: "{{ keycloak.home }}/conf/my_keycloak_key.pem"
```
This change will break your previous configuration (unless you use the default values).
To fix your config for the new changes, you will have use full paths for the 2 variables mentioned above. For example:
```
keycloak_quarkus_key_file: "/etc/ssl/certs/my_keycloak_key.pem"
keycloak_quarkus_cert_file: "/etc/ssl/certs/my_keycloak_cert.pem"
```
> keycloak_quarkus: use absolute path for certificate files

- molecule/quarkus/converge.yml
- molecule/quarkus/verify.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/templates/keycloak.service.j2
- roles/keycloak_quarkus/vars/main.yml
- Enables keycloak_quarkus role to use keycloak in dev mode by setting "keycloak_quarkus_start_dev" to True
- Fixes the hardcoded health check url in keycloak_quarkus role
> keycloak_quarkus: variable to enable development mode

- roles/keycloak/defaults/main.yml
- roles/keycloak/meta/argument_specs.yml
- roles/keycloak_realm/tasks/main.yml
- roles/keycloak_realm/tasks/manage_client_roles.yml
- roles/keycloak_realm/tasks/manage_user_roles.yml
@guidograzioli WDYT? I'm pretty user will need to switch no_log to False for debugging purpose, so rather than having them edit the installed collection, this seems to be a better approach...
> allows user to switch no_log to True for debugging purpose

- galaxy.yml
- roles/keycloak/defaults/main.yml
- roles/keycloak/meta/argument_specs.yml
- roles/keycloak/tasks/restart_keycloak.yml
- roles/keycloak/tasks/start_keycloak.yml
A small tweak, but I suspect many users we'll need to fine tune this depending on their env
> Allow overrides for service start retries and delay

- molecule/default/converge.yml
- roles/keycloak/README.md
- roles/keycloak/defaults/main.yml
- roles/keycloak/meta/argument_specs.yml
- roles/keycloak/tasks/main.yml
- roles/keycloak/templates/standalone-infinispan.xml.j2
- roles/keycloak/templates/standalone.xml.j2
- roles/keycloak/vars/main.yml
Provide a new variable:
|`keycloak_modcluster_urls` | List of {host,port} dicts for the modcluster reverse proxies | `[ { localhost:6666 } ]` |
that allows to setup multiple reverse proxy instances for the modcluster subsystem.
The variables `keycloak_modcluster_url` and `keycloak_modcluster_port` are now _deprecated_ and will be removed in the next major release.
Also provide a variable:
|`keycloak_modcluster_enabled`| Enable configuration for modcluster subsystem | `True` if `keycloak_ha_enabled` is True, else `False` |
which allows to turn on the modcluster configuration even when `modcluster_ha_enabled` is False.
Fix #56
Fix #59
> Provide config for multiple modcluster proxies

- galaxy.yml
- plugins/doc_fragments/attributes.py
- plugins/doc_fragments/keycloak.py
- plugins/module_utils/identity/keycloak/keycloak.py
- plugins/modules/keycloak_client.py
- plugins/modules/keycloak_role.py
- plugins/modules/keycloak_user_federation.py
- requirements.yml
- roles/keycloak_realm/tasks/main.yml
- roles/keycloak_realm/tasks/manage_client_roles.yml
This involves an hard-fork of a few community.general modules :(
> Drop community.general from dependencies

- roles/keycloak/README.md
- roles/keycloak/defaults/main.yml
- roles/keycloak/meta/argument_specs.yml
- roles/keycloak/tasks/install.yml
- roles/keycloak/templates/standalone-infinispan.xml.j2
When `keycloak_ha_enabled` (and `keycloak_db_enabled` also is in that case), the cluster discover protocol defaults to `JDBC_PING`. A new variable allows to set `TCPPING` as the discovery protocol instead, using the ansible play batch nodes as initial_nodes.
|`keycloak_ha_discovery`| Discovery protocol for HA cluster members | `JDBC_PING` if keycloak_db_enabled else `TCPPING` |
Fix #58
> Allow to configure TCPPING for discovery

- plugins/filter/version_sort.py
- plugins/module_utils/version.py
- roles/keycloak/README.md
- roles/keycloak/meta/argument_specs.yml
- roles/keycloak/tasks/rhsso_patch.yml
The change only applies to Red Hat Single Sign-On
> Switch to middleware_automation.common for rh-sso patching

- roles/keycloak/README.md
- roles/keycloak/defaults/main.yml
- roles/keycloak/meta/argument_specs.yml
- roles/keycloak/tasks/install.yml
- roles/keycloak/tasks/prereqs.yml
- roles/keycloak/templates/standalone-ha.xml.j2
- roles/keycloak/vars/main.yml
New parameter:
|`keycloak_remote_cache_enabled`| Enable remote cache store when in clustered ha configurations | `True` if `keycloak_ha_enabled` else `False` |
allows to setup a keycloak HA configuration without an infinispan remote cache store.
Fix #65
> Allow to setup keycloak HA cluster without remote cache store

- roles/keycloak/README.md
- roles/keycloak/defaults/main.yml
- roles/keycloak/meta/argument_specs.yml
- roles/keycloak/tasks/prereqs.yml
- roles/keycloak/vars/main.yml
Tested locally inside a docker container and a "real" SQL server
> Close #74 - add `sqlserver` support to keycloak role

- roles/keycloak/README.md
- roles/keycloak/defaults/main.yml
- roles/keycloak/meta/argument_specs.yml
- roles/keycloak/tasks/install.yml
- roles/keycloak/templates/keycloak.service.j2
Introduce a flag variable that allows to setup systemd restart behaviour, and additional variables to fine-tune it:
|`keycloak_service_restart_on_failure`| systemd restart-on-failure behavior activation |True
|`keycloak_service_startlimitintervalsec`| systemd StartLimitIntervalSec | `300` if `keycloak_service_restart_on_failure` else ``
|`keycloak_service_startlimitburst`| systemd StartLimitBurst | `5` if `keycloak_service_restart_on_failure` else ``
|`keycloak_service_restartsec`| systemd RestartSec | `10s` if `keycloak_service_restart_on_failure` else ``
Fix #80
> Introduce systemd unit restart behavior

- roles/keycloak/README.md
- roles/keycloak/defaults/main.yml
- roles/keycloak/meta/argument_specs.yml
- roles/keycloak/templates/standalone-ha.xml.j2
- roles/keycloak/templates/standalone-infinispan.xml.j2
- roles/keycloak/templates/standalone.xml.j2
- roles/keycloak/vars/main.yml
It is now possible to set the behaviour for database connection validation using the following parameters:
|`keycloak_db_background_validation` | Enable background validation of database connection | `False` |
|`keycloak_db_background_validation_millis`| How frequenly the connection pool is validated in the background | `10000` if background validation enabled |
|`keycloak_db_background_validate_on_match` | Enable validate on match for database connections | `False` |
Note that the keycloak setting configured with keycloak_db_background_validation is deprecated; also, having keycloak_db_background_validation set to false, and a non-zero keycloak_db_background_validation_millis will produce an incorrect …
> Add configuration for database connection pool validation

- roles/keycloak/README.md
- roles/keycloak/defaults/main.yml
- roles/keycloak/meta/argument_specs.yml
- roles/keycloak/templates/standalone-ha.xml.j2
- roles/keycloak/templates/standalone-infinispan.xml.j2
- roles/keycloak/templates/standalone.xml.j2
- roles/keycloak/vars/main.yml
New variable (default undefined) allows to override the URL for the administration endpoint:
| Variable | Description |
|:---------|:------------|
|`keycloak_admin_url` | Override the default administration endpoint URL |
Beware: setting `keycloak_admin_url` will require updating the configuration for the `keycloak_realm` role which consumes the API at the default endpoint.
Fix #83
> Allow to configure administration endpoint URL

- roles/keycloak/vars/main.yml
`org.mariadb.jdbc.MySQLDataSource` is [deprecated since driver version 1.3.1](https://javadoc.io/doc/org.mariadb.jdbc/mariadb-java-client/1.3.1/org/mariadb/jdbc/MySQLDataSource.html) and has been removed on 3.x.
Since the introduction of `org.mariadb.jdbc.MariaDbDataSource`, `org.mariadb.jdbc.MySQLDataSource` has always been just an alias.
A better value for this key should be `org.mariadb.jdbc.MariaDbDataSource`.
> Change xa_datasource_class value for mariadb jdbc configuration

- roles/keycloak/README.md
- roles/keycloak/defaults/main.yml
- roles/keycloak/meta/argument_specs.yml
- roles/keycloak/templates/keycloak.service.j2
... by allowing the user to freely choose from all [available values supported by systemd](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=):
* `no`
* `always`
* `on-success`
* `on-failure`
* `on-abnormal`
* `on-abort`
* `on-watchdog`
> Improve service restart behavior configuration

- roles/keycloak/README.md
- roles/keycloak/defaults/main.yml
- roles/keycloak/meta/argument_specs.yml
- roles/keycloak/templates/standalone-ha.xml.j2
- roles/keycloak/templates/standalone-infinispan.xml.j2
New optional variable:
| Variable | Description |
|:---------|:------------|
|`keycloak_jgroups_subnet`| Override the subnet match for jgroups cluster formation; if not defined, it will be inferred from local machine route configuration |
allows to statically override the `<subnet-match value=".."/>` for the `<interface name="jgroups">`.
If left undefined (default), the subnet match is computed as:
(ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ansible.utils.ipaddr('net')
The above won't work when instances are isolated (on a a.b.c.d/32 network)
> Allow to override jgroups subnet

- roles/keycloak/defaults/main.yml
Setting an empty string default for `keycloak_db_valid_conn_sql` results in an empty value in the configuration file. We should rely on defaults set fo `keycloak_jdbc.[database].validate_query`.
The alternative cloud be using `"{{ keycloak_db_valid_conn_sql | default('select 1', true) }}"` value for `keycloak_jdbc.[database].validate_query`
> Undefine `keycloak_db_valid_conn_sql` default

- .github/workflows/ci.yml
- molecule/default/verify.yml
- roles/keycloak/tasks/systemd.yml
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/tasks/systemd.yml
This change also update ci to run molecule with matrix.
> keycloak_quarkus: set openjdk 17 as default

- molecule/overridexml/converge.yml
- roles/keycloak/README.md
- roles/keycloak/defaults/main.yml
- roles/keycloak/meta/argument_specs.yml
- roles/keycloak/tasks/install.yml
- roles/keycloak/templates/keycloak-sysconfig.j2
- roles/keycloak/templates/keycloak.service.j2
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
The actual implementation always runs the service as root user.
This PR uses the existing variables `keycloak_service_user` and `keycloak_service_group`  to set the user and group of the startup script and so of the actual java process.
I have also changed the default `keycloak_service_pidfile` value allowing to set the correct permissions on the folder containing the pidfile
> Run service as `keycloak_service_user`

- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
|`keycloak_quarkus_proxy_mode`| The proxy address forwarding mode if the server is behind a reverse proxy. Allowed values are: [ none, edge, reencrypt, passthrough ] | `edge` |
> keycloak_quarkus: skip proxy config if `keycloak_quarkus_proxy_mode` is `none`

- playbooks/keycloak_quarkus_dev.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
> Fix admin login redirect when running locally

- roles/keycloak_quarkus/tasks/main.yml
Ensure to run the `restart keycloak` handler before attempting to validate service status.
Otherwise changing `keycloak_quarkus_http_port` always lead to a failing play because the wait until service up is targeting the new port but the service has not restarted yet.
> Fix validation failure upon port configuration change

- molecule/quarkus/prepare.yml
- molecule/quarkus/verify.yml
prepare playbook was failing for me when running quarkus suite locally (can't/won't edit my hosts file via sudo).
If it just for having `curl` in the verify playbook to succeed, this should be enough.
(didn't really understood what this HERA_HOME stuff is for)
> Do not require hosts edit for running quarkus molecule suite locally

- molecule/quarkus/converge.yml
- playbooks/keycloak_quarkus.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
I hope that my changes meet your acceptance criteria.
> [keycloak_quarkus] Enable config of a key store and trust store

- playbooks/keycloak_quarkus.yml
As defined in the [role documentation](https://github.com/ansible-middleware/keycloak/tree/main/roles/keycloak_quarkus#role-variables) the correct variable to use is `keycloak_quarkus_admin_pass` not `keycloak_admin_password` .
> Update admin password variable in keycloak_quarkus.yml

- .github/workflows/ci.yml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
Since keycloak 23.x, keycloak.conf requires bool parameters to be lowercase.
fix #136
> Update template to lowercase booleans

- roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
Note: when multiple -X options of the same kind are provided, the last option seems to take precendence as per <https://stackoverflow.com/a/26727332>:
> java -Xmx1G -XX:+PrintFlagsFinal -Xmx2G 2>/dev/null | grep MaxHeapSize
> fix/#153: keycloak_quarkus: Use `keycloak_quarkus_java_opts`

- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
> keycloak_quarkus: allow configuration of `hostname-strict-backchannel`

- roles/keycloak_quarkus/templates/keycloak.service.j2
> keycloak_quarkus: allow ports <1024 (e.g. :443) in systemd unit

- galaxy.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/templates/quarkus.properties.j2
This changeset contains a parameter rename for the `keycloak_quarkus` role, which reflects a renaming that happened in the upstream project. 
The removed parameter is `keycloak_quarkus_ispn_url`, which is superseeded by:
|`keycloak_quarkus_ispn_hosts` | semicolon separated `hostname:port` for connecting to infinispan, eg. `host1:11222;host2:11222` | `localhost:11222` |
Fix #146 
Fix #156
> keycloak_quarkus: renamed infinispan host list configuration

- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/handlers/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/tasks/main.yml
- roles/keycloak_quarkus/tasks/rebuild_config.yml
- roles/keycloak_quarkus/templates/cache-ispn.xml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
- roles/keycloak_quarkus/templates/keycloak.service.j2
* changes port of TCPPING to 7800/tcp (was: 7600/tcp, based on JDBCPING which was default in keycloak role)
* adds `kc.sh build` invocation in order to minimize startup time; moreover, I had issues with getting TCPPING config to work since  keycloak, upon a regular invocation of `kc.sh start` creates it's own internal cache which is kept until a build is re-run; this newly added handler will save us some headaches in future
* adds `kc.sh start --optimized` in case `--start-dev` is not executed, thus re-using the aforementioned pre-built configuration
Fix #158
> #158: Feature/inifinispan TCPPING

- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/templates/quarkus.properties.j2
New role parameters allow to tweak log rotation:
|`keycloak_quarkus_log_max_file_size`| Set the maximum log file size before a log rotation happens; A size configuration option recognises string in this format (shown as a regular expression): `[0-9]+[KkMmGgTtPpEeZzYy]?`. If no suffix is given, assume bytes. | `10M` |
|`keycloak_quarkus_log_max_backup_index`| Set the maximum number of archived log files to keep" | `10` |
|`keycloak_quarkus_log_file_suffix`| Set the log file handler rotation file suffix. When used, the file will be rotated based on its suffix; Note: If the suffix ends with `.zip` or `.gz`, the rotation file will also be compressed. | `.yyyy-MM-dd.zip` |
Fix #160
> keycloak_quarkus: Allow configuring log rotate options in quarkus configuration

- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
New extremely long unimaginatively named parameter (do not blame the collection):
|`keycloak_quarkus_spi_sticky_session_encoder_infinispan_should_attach_route`| If the route should be attached to cookies to reflect the node that owns a particular session. If false, route is not attached to cookies and we rely on the session affinity capabilities from reverse proxy | `True` |
allows to configure the corresponding option.
Fix #163
> keycloak_quarkus: `sticky-session`s for infinispan routes

- roles/keycloak_quarkus/templates/quarkus.properties.j2
Since when XA-transaction default was set to true, bootstrapping produces the following warning:
```
WARN [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. 
Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, 
otherwise data may be lost if the application is terminated abruptly
```
> Set enable-recovery when xa transactions are enabled

- molecule/https_revproxy/prepare.yml
- molecule/quarkus-devmode/converge.yml
- molecule/quarkus-devmode/prepare.yml
- molecule/quarkus-devmode/verify.yml
- roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
Fix parameter documented as `keycloak_quarkus_java_home`, but internally referred as `keycloak_java_home`, to be referenced as `keycloak_quarkus_java_home`
Fix #170
> keycloak_quarkus: fix custom JAVA_HOME parameter name

- molecule/overridexml/templates/custom.xml.j2
- roles/keycloak/templates/15.0.8/standalone-infinispan.xml.j2
- roles/keycloak/templates/15.0.8/standalone.xml.j2
- roles/keycloak/templates/keycloak-service.sh.j2
- roles/keycloak/templates/keycloak-sysconfig.j2
- roles/keycloak/templates/keycloak.service.j2
- roles/keycloak/templates/standalone-ha.xml.j2
- roles/keycloak/templates/standalone-infinispan.xml.j2
- roles/keycloak/templates/standalone.xml.j2
- roles/keycloak_quarkus/templates/cache-ispn.xml.j2
- roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
- roles/keycloak_quarkus/templates/keycloak.conf.j2
- roles/keycloak_quarkus/templates/keycloak.service.j2
- roles/keycloak_quarkus/templates/quarkus.properties.j2
Changes all template files that include the ```{{ ansible_managed }}``` annotation  to include  ```{{ ansible_managed | comment  }}``` or, in case of XML templates , ```{{ ansible_managed | comment('xml')  }}``` instead. 
Documentation: [Ansible: manipulating-text](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#manipulating-text)
The ```{{ ansible_managed }}``` vairable is configurable via the ```ansible.cfg``` file and can be a **multiline string** in which case the form ```# {{ ansible_managed }}``` used in keycloak.conf.j2,  keycloak.service.j2 and keycloak-sysconfig.j2 breaks the file. XML templates that use `````` are ok and I only changed them for consistency.
```ansible.cfg```
```
ansible_managed = WARNING: This file is managed by ANSIBLE.
template: …
```
> Utilize comment filter for `ansible_managed` annotations

- roles/keycloak_quarkus/tasks/install.yml
When installing onto a remote node, the locally-created ZIP file appears to be created as root.
Fix #125
> Fix permissions on controller-side downloaded artifacts

- molecule/default/converge.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
The role parameter `keycloak_quarkus_java_opts` now contains all arguments passed concatenated to the JVM, and it is used to value the `JAVA_OPTS` environment variable read be `kc.sh`. 
By dafault, it takes the contatenation of two new arguments:
|`keycloak_quarkus_java_opts`| Heap memory JVM setting | `-Xms1024m -Xmx2048m` |
|`keycloak_quarkus_java_jvm_opts`| Other JVM settings | same as keycloak |
|`keycloak_quarkus_java_opts`| JVM arguments; if overriden, it takes precedence over `keycloak_quarkus_java_*` | `{{ keycloak_quarkus_java_heap_opts + ' ' + keycloak_quarkus_java_jvm_opts }}` |
Fix #185
> JVM arguments go in JAVA_OPTS

- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
- roles/keycloak_quarkus/templates/keycloak.service.j2
- Via created a new optional variable : keycloak_quarkus_proxy_headers
- Fix enhancement #183
- see https://www.keycloak.org/server/reverseproxy about the official keycloak documentation
> Permit parse reverse proxy headers

- roles/keycloak_quarkus/tasks/install.yml
- roles/keycloak_quarkus/tasks/jdbc_driver.yml
- roles/keycloak_quarkus/tasks/main.yml
- roles/keycloak_quarkus/tasks/systemd.yml
Restrict permission on some root-owned configuration files from 644 to 640
> Unrelax configuration file permissions

- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/handlers/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/tasks/config_store.yml
- roles/keycloak_quarkus/tasks/deprecations.yml
- roles/keycloak_quarkus/tasks/main.yml
- roles/keycloak_quarkus/tasks/prereqs.yml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
- roles/keycloak_quarkus/vars/main.yml
`keytool` might not be the best tool for this, but I didn't find any better: `openssl` does support PKCS12 stores, but does not allow for creating PBEs (password-based entries); 
Note that this has a breaking change since variables had to be renamed to reduce confusion.
Open for any improvements, but I didn't find a more ansiblish way to do it since keytool doesn't allow for reading the actual secret values, only whether it exists or not.
Moreover let me know if you see more variables from `keycloak.conf` that would fit into this key store, thanks.
> #188: add support for configuration key store

- molecule/quarkus/converge.yml
- molecule/quarkus/prepare.yml
- molecule/quarkus/verify.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/handlers/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
Add parameters that allow to configure keystore-based vault SPI:
Role Defaults
-------------
|`keycloak_quarkus_ks_vault_enabled`| Whether to enable the vault SPI | `false` |
|`keycloak_quarkus_ks_vault_file`| The keystore path for the vault SPI | `{{ keycloak_quarkus_config_dir }}/keystore.p12` |
|`keycloak_quarkus_ks_vault_type`| Type of the keystore used for the vault SPI | `PKCS12` |
Role Variables
--------------
| Variable | Description | Required |
|:---------|:------------|----------|
|`keycloak_quarkus_ks_vault_pass`| The password for accessing the keystore vault SPI | `no` |
See: https://www.keycloak.org/server/vault#_configuring_the_java_keystore_based_vault
Also see molecule/quarkus/converge.yml for usage …
> Keystore based vault SPI

- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/handlers/main.yml
- roles/keycloak_quarkus/tasks/bootstrapped.yml
- roles/keycloak_quarkus/tasks/install.yml
- roles/keycloak_quarkus/tasks/main.yml
- roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
- roles/keycloak_quarkus/templates/keycloak.fact.j2
- roles/keycloak_quarkus/vars/main.yml
@guidograzioli this is my take on #190:
This approach could be troublesome when the state file (`/etc/sysconfig/keycloak`) contains the bootstrapped mnemonicer already, but we are switching DBs where the new DB is completely empty.
But I guess this edge case would be ok favoring hiding these sensitive credentials on the long term, worst case one needs to set `keycloak_quarkus_purge_admin_credentials_after_bootstrapping=True` and then run the playbook once more.
Wdyt?
> #190: remove `keycloak_quarkus_admin_user[_pass]` once keycloak is bootstrapped

- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
Resolves #193 
Added a new option `keycloak_quarkus_hostname_strict_https` with no default value.
If the option is set, the Jinja template for `keycloak.conf.j2` checks to see if the value is either `true` or `false` and applies it appropriately
> Added hostname-strict-https option

- molecule/quarkus/converge.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/tasks/install.yml
- roles/keycloak_quarkus/tasks/prereqs.yml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
|`keycloak_quarkus_providers`| List of provider definitions; see below | `[]` |
Provider definition:
```yaml
keycloak_quarkus_providers:
- id: http-client                         # required
spi: connections                        # required if url is not specified
default: true                           # optional, whether to set default for spi, default false
restart: true                           # optional, whether to restart, default true
url: https://.../.../custom_spi.jar     # optional, url for download
properties:                             # optional, list of key-values
- key: default-connection-pool-size
value: 10
```
the definition above will generate the same configuration as the following build …
> Providers config and custom providers

- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/tasks/jdbc_driver.yml
Add three new parameters which allow for overriding the download URL for the JDBC driver and also specifying credentials for downloading those JDBC drivers.
| Variable | Description | Required |
|`keycloak_quarkus_jdbc_download_url`| Override the default Maven Central download URL for the JDBC driver | `no` |
|`keycloak_quarkus_jdbc_download_user`| Set a username with which to authenticate when downloading JDBC drivers from an alternative location | `no` |
|`keycloak_quarkus_jdbc_download_pass`| Set a password with which to authenticate when downloading JDBC drivers from an alternative location (requires keycloak_quarkus_jdbc_download_user) | `no` |
Resolves #200
> Customize jdbc driver downloads, optional authentication

- roles/keycloak/meta/argument_specs.yml
- roles/keycloak/tasks/jdbc_driver.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/tasks/jdbc_driver.yml
- Added jdbc_download customization to both keycloak releases
- Added option to allow invalid certificates to download JDBC drivers
Resolves #206 
I was able to test for keycloak_quarkus, but not for keycloak.
> jdbc_download and validate_certs params update

- roles/keycloak_quarkus/tasks/install.yml
Download to controller fails if playbook is run with `become: true` on sudo password promtp.
Fix #205
> controller priv escalation

- molecule/quarkus/converge.yml
- molecule/quarkus/prepare.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/tasks/install.yml
This pull request updates the configuration to use the standard Red Hat Enterprise Linux (RHEL) default path for TLS certificates.
Also, it copies the private key and certificate to the target host.
#208
> Enable copying of key material

- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/tasks/install.yml
| Variable | Description | Required |
|:---------|:------------|----------|
|`keycloak_quarkus_alternate_download_url`| Alternate location with optional authentication for downloading RHBK | `no` |
|`keycloak_quarkus_download_user`| Optional username for http authentication  | `no*` |
|`keycloak_quarkus_download_pass`| Optional password for http authentication | `no*` |
|`keycloak_quarkus_download_validate_certs`| Whether to validate certs for URL `keycloak_quarkus_alternate_download_url`  (if omitted, do validate) | `no` |
`*` username/password authentication credentials must be both declared or both undefined
> Download from alternate URL with optional http authentication

- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/tasks/prereqs.yml
- roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
New parameter:
|`keycloak_quarkus_additional_env_vars` | List of additional env variables of { key: str, value: str } to be put in sysconfig file | `[]` |
Close #228
> Allow to add extra custom env vars in sysconfig file

- molecule/quarkus/converge.yml
- requirements.txt
- requirements.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/tasks/install.yml
- roles/keycloak_quarkus/tasks/prereqs.yml
Extends support for custom providers ("SPIs"): while previously only http downloads were supported, the new provider definition allows for maven downloads (e.g., Apache Maven Central,  Github Apache Maven (requires authn via a PAT)).
The new providers definition looks like:
```yaml
keycloak_quarkus_providers:
- id: http-client                         # required
spi: connections                        # required if url is not specified
- id: http-client                         # required; "{{ id }}.jar" identifies the file name on RHBK
spi: connections                        # required if neither url, local_path nor maven are specified; required for setting properties
default: true                           # optional, whether to set default for spi, default false
restart: true …
```
> Allow for custom providers hosted on maven repositories

- molecule/debian/converge.yml
- molecule/https_revproxy/converge.yml
- molecule/quarkus-devmode/converge.yml
- molecule/quarkus/converge.yml
- molecule/quarkus_ha/converge.yml
- molecule/quarkus_upgrade/converge.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/tasks/deprecations.yml
- roles/keycloak_quarkus/tasks/prereqs.yml
- roles/keycloak_quarkus/templates/keycloak.conf.j2
Deprecated `proxy` setting will only be emitted in keycloak.conf if `keycloak_quarkus_proxy_headers` is not set.
Fix #226
> `proxy-header` enhancement

- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
New default for `keycloak_quarkus_restart_health_check` is `true` (was: true if `keycloak_quarkus_ha_enabled`).
Fix #233
> Enable by default health check on restart

- .ansible-lint
- .gitignore
- molecule/default/converge.yml
- molecule/default/prepare.yml
- molecule/default/verify.yml
- molecule/quarkus/prepare.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/handlers/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/tasks/bootstrapped.yml
- roles/keycloak_quarkus/tasks/config_store.yml
- roles/keycloak_quarkus/tasks/install.yml
- roles/keycloak_quarkus/tasks/main.yml
- roles/keycloak_quarkus/tasks/prereqs.yml
- roles/keycloak_quarkus/tasks/rebuild_config.yml
- roles/keycloak_quarkus/tasks/restart.yml
The new parameter allows to specify the path to be used on controller for downloading install tarballs.
|`keycloak_quarkus_download_path`| Path local to controller for offline/download of install archives | `{{ lookup('env', 'PWD') }}` |
The default is backwards compatible so no change is necessary; when an offline install is performed, existence of install tarballs is checked in the specified path before starting installation.
Internal: CI molecule test `default` now tests keycloak in offline mode (instead of keycloak-legacy)
Fix #238
> New parameter `keycloak_quarkus_download_path` 

- roles/keycloak_realm/tasks/main.yml
- roles/keycloak_realm/tasks/manage_user_client_roles.yml
See #256.
Most, but not all steps in the `keycloak_realm` tasks skip checking SSL certificates.
Since e.g. in `roles/keycloak_realm/tasks/main.yml` the first step `Generate keycloak auth token` has set
`validate_certs: false`, but the next step `Determine if realm exists` does not, I assume this was a mistake?
I briefly checked the other tasks in `roles/keycloak_realm/tasks/` and added `validate_certs: false` where it was missing.
With those changes, the tasks now work for my setup with self-signed certificates.
> Skip certificate checking

- CONTRIBUTING.md
- README.md
- docs/requirements.txt
- galaxy.yml
- meta/runtime.yml
- molecule/default/molecule.yml
- molecule/https_revproxy/molecule.yml
- molecule/overridexml/molecule.yml
- molecule/quarkus-devmode/molecule.yml
- molecule/quarkus/converge.yml
- molecule/quarkus/molecule.yml
- molecule/quarkus/verify.yml
- molecule/quarkus_ha/molecule.yml
- roles/keycloak/meta/main.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/meta/main.yml
- roles/keycloak_quarkus/tasks/restart.yml
- roles/keycloak_quarkus/tasks/start.yml
- roles/keycloak_realm/meta/main.yml
Start collection version 3.0
Update minimum ansible-core requirement to 2.16+
Fix spell in parameter `keycloak_quarkus_restart_health_check_retries`
> Bump major and ansible-core versions

- roles/keycloak/defaults/main.yml
- roles/keycloak/vars/main.yml
- roles/keycloak_realm/defaults/main.yml
- roles/keycloak_realm/vars/main.yml
Role parameters `keycloak_url` and `keycloak_management_url`, formerly variables, are turned into default to make overriding them easier. Default values are unchanged.
Issue: https://issues.redhat.com/browse/AMW-384
GitHub Issue: https://github.com/ansible-middleware/keycloak/issues/265
> keycloak_realm: change url variables to defaults

- playbooks/keycloak_quarkus.yml
- playbooks/keycloak_quarkus_dev.yml
When running the quarkus role using the example provided in the repo, it fails with:
```
TASK [middleware_automation.keycloak.keycloak_quarkus : Validating arguments against arg spec 'main'] *********************************************************************************************************************
fatal: [91.99.14.247]: FAILED! => {"argument_errors": ["argument 'keycloak_quarkus_bootstrap_admin_password' is of type <class 'NoneType'> and we were unable to convert to str:
```
This replaces the deprecated `keycloak_admin_password` with `keycloak_quarkus_bootstrap_admin_password`.
> Update example playbooks to use new `bootstrap` var

- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/tasks/deprecations.yml
- roles/keycloak_quarkus/templates/cache-ispn.xml.j2
- roles/keycloak_quarkus/templates/keycloak.conf.j2
Parameter rename and add in configuration since it was missing:
| Name                                           | Replacement (requires manual adaptation)   | Reason                                                                                               |
| ---------------------------------------------- | ----------------------------------------------- | ----------------------------------------------------------- |
| `keycloak_quarkus_bind_address`         | `keycloak_quarkus_http_host`  | [HTTP configuration](https://www.keycloak.org/server/all-config#category-http)  |
`keycloak_quarkus_bind_address` remains as deprecated, when used a deprecation warning will be emitted and the variable will be used.
Labelled as bugfix and not breaking change even if it contains a rename, because …
> Rename and honour parameter `keycloak_quarkus_http_host`

- molecule/debian/prepare.yml
- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/defaults/main.yml
- roles/keycloak_quarkus/meta/argument_specs.yml
- roles/keycloak_quarkus/tasks/main.yml
This is useful if the default route does not
represent the network you want/need to use for
cluster communication.
> New parameter to set the jgroups host IP address

- roles/keycloak_quarkus/tasks/install.yml
26.2 is stricter when it comes to validating its optimized config and thus refuses to start in case a SPI was deployed w/o properly having invoked `kc.sh build` first (related: https://github.com/keycloak/keycloak/issues/37770)
> Run config rebuild after SPI providers update

- molecule/debian/molecule.yml
- molecule/debian/prepare.yml
- roles/keycloak_quarkus/vars/debian.yml
> Use jdk21 as default in debian

- roles/keycloak_quarkus/tasks/install.yml
Even is we set keycloak_quarkus_alternate_download_url previous block was run and we always try to download archive from JBoss Network Api.
> Fix alternate download location being ignored (JBossNeworkAPI always used)

- roles/keycloak_realm/README.md
- roles/keycloak_realm/tasks/main.yml
`keycloak_clients` can now configure client secret.
```yaml
keycloak_clients:
- name: MyAwesomeClient
client_id: awesomeclient
secret: changeme
realm: "myrealm
```
Fix #301
> keycloak_realm: allow secret in keycloak_clients

- roles/keycloak_quarkus/README.md
- roles/keycloak_quarkus/meta/argument_specs.yml
Small fix to update description for keycloak_quarkus_config_key_store_file variable in order to match the password variable name.
> Fix config_key_store_file description to match variable name
