ansible-middleware/keycloak

roles/keycloak/tasks/systemd.yml
@guidograzioli what do you think?
=> Enhance wait message with keycloak healthcheck URL

README.md, ansible_hosts, playbooks/keycloak-realm.yml, playbooks/keycloak.yml
- Separated Keycloak installation and configuration.
- Updated README.md as per current changes.
=> Separate playbooks for installation and configuration

roles/keycloak_realm/tasks/main.yml
=> User federation

.ansible-lint, .github/workflows/ci.yml, galaxy.yml, molecule/default/molecule.yml, roles/keycloak/README.md, roles/keycloak/tasks/fastpackages/check.yml, roles/keycloak/tasks/fastpackages/install.yml, roles/keycloak/tasks/install.yml, roles/keycloak/tasks/main.yml, roles/keycloak/tasks/systemd.yml, roles/keycloak_realm/README.md
Use helper scripts for argument_specs from https://github.com/ansible-middleware/collections-helper-scripts
And validate using custom rules from https://github.com/ansible-middleware/ansible-lint-custom-rules
=> READMEs updated by helper scripts

molecule/default/prepare.yml, molecule/default/verify.yml, playbooks/keycloak.yml, playbooks/keycloak_realm.yml, playbooks/rhsso.yml, roles/keycloak/handlers/main.yml, roles/keycloak/tasks/fastpackages/check.yml, roles/keycloak/tasks/fastpackages/install.yml, roles/keycloak/tasks/firewalld.yml, roles/keycloak/tasks/install.yml, roles/keycloak/tasks/main.yml, roles/keycloak/tasks/prereqs.yml, roles/keycloak/tasks/restart_keycloak.yml, roles/keycloak/tasks/stop_keycloak.yml, roles/keycloak/tasks/systemd.yml, roles/keycloak_realm/tasks/main.yml, roles/keycloak_realm/tasks/manage_client_roles.yml, roles/keycloak_realm/tasks/manage_client_users.yml, roles/keycloak_realm/tasks/manage_user.yml, roles/keycloak_realm/tasks/manage_user_client_roles.yml, roles/keycloak_realm/tasks/manage_user_roles.yml
Replace all module names with fully qualified version
=> fix: use FQCN

roles/keycloak/README.md, roles/keycloak/defaults/main.yml, roles/keycloak/meta/argument_specs.yml, roles/keycloak/tasks/main.yml, roles/keycloak/tasks/rhsso_cli.yml, roles/keycloak/tasks/rhsso_patch.yml, roles/keycloak/tasks/stop_keycloak.yml, roles/keycloak/templates/standalone-infinispan.xml.j2, roles/keycloak/vars/main.yml
- add tasks for running cli
- add tasks and config for downloading latest patch, and apply via cli
Fixes #14
=> Change to allow installation of latest RHSSO patch

roles/keycloak/README.md, roles/keycloak/defaults/main.yml, roles/keycloak/handlers/main.yml, roles/keycloak/meta/argument_specs.yml, roles/keycloak/tasks/prereqs.yml, roles/keycloak/templates/keycloak.service.j2
Fix #24 
Also contains a parameter rename: jvm_package -> keycloak_jvm_package
=> Set the frontend URL to play well with other defaults

molecule/default/converge.yml, molecule/default/verify.yml, roles/keycloak_realm/tasks/main.yml
=> Pass attributes to realm clients

roles/keycloak/templates/15.0.8/standalone-infinispan.xml.j2, roles/keycloak/templates/9.0.2/standalone-infinispan.xml.j2, roles/keycloak/templates/standalone-ha.xml.j2, roles/keycloak/templates/standalone-infinispan.xml.j2
=> Fix deprecation warning for `ipaddr`

README.md
=> add certified collection notice

roles/keycloak/tasks/prereqs.yml, roles/keycloak_quarkus/tasks/prereqs.yml
Workaround for bugzilla  [#2224411](https://bugzilla.redhat.com/show_bug.cgi?id=2224411)
=> fix_java_11_tzdata

molecule/default/converge.yml, molecule/default/verify.yml, molecule/quarkus/converge.yml, molecule/quarkus/verify.yml, roles/keycloak/README.md, roles/keycloak/defaults/main.yml, roles/keycloak/meta/argument_specs.yml, roles/keycloak/tasks/main.yml, roles/keycloak_quarkus/README.md, roles/keycloak_quarkus/defaults/main.yml, roles/keycloak_quarkus/meta/argument_specs.yml, roles/keycloak_quarkus/tasks/main.yml
=> feat: add a destination variable for the log link

README.md
Issue: https://issues.redhat.com/browse/AMWSUP-17
=> AMWSUP-17 keycloak Ansible Hub documentation link broken

README.md
Issue: https://issues.redhat.com/browse/AMW-170
=> AMW-170 Ansible Hub links for rhbk are broken

galaxy.yml, roles/keycloak_quarkus/README.md, roles/keycloak_quarkus/defaults/main.yml, roles/keycloak_quarkus/meta/argument_specs.yml, roles/keycloak_quarkus/templates/keycloak.service.j2
=> keycloak_quarkus: systemd restart behavior

roles/keycloak_quarkus/README.md, roles/keycloak_quarkus/defaults/main.yml, roles/keycloak_quarkus/meta/argument_specs.yml, roles/keycloak_quarkus/tasks/install.yml, roles/keycloak_quarkus/tasks/jdbc_driver.yml
=> keycloak_quarkus: Add support for sqlserver jdbc driver

roles/keycloak_quarkus/tasks/jdbc_driver.yml
=> Fix logic in when clause

.github/workflows/ci.yml, molecule/quarkus_upgrade/converge.yml, molecule/quarkus_upgrade/molecule.yml, molecule/quarkus_upgrade/prepare.yml, molecule/quarkus_upgrade/vars.yml, molecule/quarkus_upgrade/verify.yml
=> Port downstream upgrade

roles/keycloak_quarkus/README.md, roles/keycloak_quarkus/tasks/install.yml
=> Rebuild config and restart service for local providers

.github/workflows/ci.yml, roles/keycloak_realm/tasks/main.yml, roles/keycloak_realm/tasks/manage_token_lifespan.yml
Issue: https://github.com/ansible-middleware/keycloak/issues/247
=> Access token lifespan is too short for ansible run

molecule/quarkus/converge.yml, roles/keycloak_quarkus/tasks/rebuild_config.yml, roles/keycloak_quarkus/tasks/systemd.yml, roles/keycloak_quarkus/templates/keycloak-sysconfig.j2, roles/keycloak_quarkus/vars/debian.yml, roles/keycloak_quarkus/vars/redhat.yml
A change to environment file now triggers a server rebuild.
Fix #273
=> Load environment vars during kc rebuild

molecule/quarkus_upgrade/converge.yml, molecule/quarkus_upgrade/prepare.yml, roles/keycloak_quarkus/tasks/systemd.yml
=> Trigger rebuild handler on envvars file change

molecule/quarkus/converge.yml, roles/keycloak_quarkus/README.md, roles/keycloak_quarkus/tasks/install.yml
=> New `checksum` property for keycloak_quarkus_providers

molecule/quarkus_ha_remote/converge.yml, roles/keycloak_quarkus/README.md, roles/keycloak_quarkus/defaults/main.yml, roles/keycloak_quarkus/meta/argument_specs.yml, roles/keycloak_quarkus/templates/keycloak.conf.j2
https://www.keycloak.org/server/caching
https://www.keycloak.org/2024/12/storing-sessions-in-kc26
=> Session storage / distributed caches

roles/keycloak_quarkus/README.md, roles/keycloak_quarkus/defaults/main.yml, roles/keycloak_quarkus/meta/argument_specs.yml, roles/keycloak_quarkus/tasks/install.yml
Issue: https://github.com/ansible-middleware/keycloak/issues/295
=> Fix `keycloak_quarkus_force_install` parameter being ignored by install
